services:
  backend:
    environment:
      WIREGUARD_PUBLIC_IPS: ${WIREGUARD_PUBLIC_IPS}
      WIREGUARD_RELAY_PUBLIC_KEY: ${WIREGUARD_RELAY_PUBLIC_KEY}
      WIREGUARD_ENDPOINT: ${WIREGUARD_ENDPOINT}
