services:
  migrate:
    environment:
      LIGHTNING_SWAP_API_KEY_FILE: ""
      LIGHTNING_SWAP_API_SECRET_FILE: ""

  backend:
    secrets:
      - source: lightning-swap-api-key
        target: lightning-swap-api-key
        uid: "10001"
        gid: "10001"
        mode: 0400
      - source: lightning-swap-api-secret
        target: lightning-swap-api-secret
        uid: "10001"
        gid: "10001"
        mode: 0400

secrets:
  lightning-swap-api-key:
    file: ${SECRETS_DIR:-./secrets}/lightning-swap-api-key
  lightning-swap-api-secret:
    file: ${SECRETS_DIR:-./secrets}/lightning-swap-api-secret
