launch=gsqlite3
gsqlite3-database=/var/lib/powerdns/pdns.sqlite3
gsqlite3-dnssec=yes
local-port=53
socket-dir=/run/pdns
enable-lua-records=yes
lua-health-checks-interval=10
cache-ttl=0
query-cache-ttl=0
negquery-cache-ttl=0
api=no
webserver=no
dnsupdate=no
disable-axfr=no
allow-unsigned-notify=yes
autosecondary=no
query-logging=no
log-dns-details=no
log-dns-queries=no
version-string=anonymous
security-poll-suffix=
default-ttl=3600
reuseport=no
receiver-threads=1
